### ISSUE TITLE
Add Image Optimization Plugin

### ISSUE THREAD

**Issue by vinkla** [vinkla/wordpress#55]
Wouldn't it be good to integrate a good image optimizer by default? Maybe [tiny-compress](https://wordpress.org/plugins/tiny-compress-images)?

```json
"wpackagist-plugin/tiny-compress": "~1.0"
```

@puredazzle @magnus-bergman do you guys have any thoughts about this topic? Does is belong in the boilerplate?

**Comment by puredazzle** [comment]
Yes, that would be a good feature to have. From my experience this is the best plugin for this cause.

**Comment by vinkla** [comment]
In your experience, is the outcome good? Does the images look good?

**Comment by puredazzle** [comment]
@vinkla yes, sometimes on very big images the colours get a little bit more damp but I haven't noticed any bigger differences. Except the size! :+1:

**Comment by magnus-bergman** [comment]
@vinkla @puredazzle All performance optimizations that are non destructive are always good in my opinion. :+1:  Maybe we should have some kind of caching plugin in the boilerplate out of the box as well? A completely different issue but important nevertheless.

**Comment by vinkla** [comment]
Great! Then it is decided. I'll open a PR asap.

**Comment by vinkla** [comment]
Merged in #57
